doc: add section about status bar segments
71/dance pull request #195
Opened 2021-09-03 13:14 UTC by Delapouite

Hi

I recently asked myself "How many status bar segments are provided by Dance?". After a small visit in the code, I think it would be a nice addition to have the answer available directly in the readme.

Thanks

2021-09-03 16:34 UTC, 71 requested changes
Thanks! A few comments:

2021-09-03 16:34 UTC, 71 commented on README.md
> +to Kakoune's default mode-line:
I would also add that most of them are hidden by default, and only shown contextually. You can either write this, or explain it individually for each segment.

2021-09-03 16:34 UTC, 71 commented on README.md
> +- dance error: click to copy the last one
nit:
```suggestion
- dance error: click to copy the full description of the last error
```

(Or something else that implies that the full error is copied, not just what's shown on the status bar, which is truncated)

2021-09-06 05:47 UTC, Delapouite commented
Thanks for the feedback. I've adjusted the text accordingly.

2021-09-06 11:03 UTC, 71 commented on README.md
> +j# Dance
Typo?

2021-09-06 16:52 UTC, 71 approved these changes
Thanks!

2021-09-06 16:52 UTC, merged